### ISSUE TITLE
Compilation Error when running mvn spring-boot:run

### ISSUE THREAD

**Issue by sachinn12** [Garrafao/phitag#60]
![Screenshot from 2023-10-05 10-41-33](https://github.com/Garrafao/phitag/assets/46670571/77ca2d54-8c65-43c4-9c16-eb984c6abe6a)

**Comment by sachinn12** [comment]
when I am trying to run backend using cmd " mvn spring-boot:run", I am getting above compilation error

**Comment by confusedSerge** [comment]
# Fix
A simple fix is to remove the offending line from the [changelog-file](https://github.com/Garrafao/phitag/blob/main/backend/src/main/resources/db/changelog/db.changelog-development.xml) (line 36). This should also be in most cases turned of for development, else starting the development environment takes a long time, as the corpus needs to be loaded. 

# Problem
The problem is, that there is no corpus seed data at the given path. This data needs to be generated and added. Due to the size of this generated data, it is not included in this repository. A good start would be to create a small set, but I have not yet come around in doing that.

**Comment by Garrafao** [comment]
Where do we find the corpus data used in the current running version of the system?

**Comment by AinaIanemahy** [comment]
This is now changed on the main branch. We should keep it in mind and change it back when we find out where to find the corpus. We might have to uncomment the relevant lines when deploying.
